SELECT PASSENGER.Fname, PASSENGER.Lname, PASSENGER.Ssn, TICKET.Status
FROM TRAIN, PASSENGER, TICKET
WHERE TRAIN.Train_name = 'Flying Scotsman' AND TRAIN.Train_num = TICKET.train_num AND TICKET.SSN = PASSENGER.SSN AND TICKET.Status = 'Booked';
