SELECT PASSENGER.Fname, PASSENGER.Lname, TRAIN.Train_name, TICKET.Status
FROM TRAIN, PASSENGER, TICKET
WHERE PASSENGER.Fname = 'Art' AND PASSENGER.Lname = 'Venere' AND PASSENGER.Ssn = TICKET.Ssn AND TICKET.Train_num = TRAIN.Train_num;
